#!/bin/bash

FILES=( src/index.html \
        src/edge_node.js \
        src/engine.js \
        src/jquery-1.9.1.min.js \
        src/mutator.js \
        src/output.js \
        src/action_distribution.js \
        change.log )
SKELETONS=skeletons/

main()
{
	make_tar_release
	make_zip_release
}

make_tar_release()
{
    tar cvf release/latest.tar ${FILES[@]} ${SKELETONS}
}

make_zip_release()
{
    zip release/latest.zip ${FILES[@]} -r ${SKELETONS}
}

main
