#!/bin/bash

FILES="src/index.html src/edge_node.js  src/engine.js  src/jquery-1.9.1.min.js  src/mutator.js  src/output.js change.log"

main()
{
	make_tar_release
	make_zip_release
}

make_tar_release()
{
    tar cvf release/latest.tar ${FILES}
}

make_zip_release()
{
    zip release/latest.zip ${FILES}
}

main
